/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.RnDRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.RnDOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGOtoRNDWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita Mhatre
 */
public class RnDWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form RnDWorkAreaJPanel
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Network network;
    private EcoSystem business;
    private UserAccount userAccount;
    public RnDWorkAreaJPanel() {
        initComponents();
    }

    public RnDWorkAreaJPanel(JPanel userProcessContainer, UserAccount userAccount, Enterprise enterprise, Network network, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.network = network;
        this.userAccount = userAccount;
        this.business = business; //To change body of generated methods, choose Tools | Templates.
        populateRnDRequestTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnProcess = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRnDProcess = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Reasearch and Development ");

        btnProcess.setBackground(new java.awt.Color(51, 153, 255));
        btnProcess.setForeground(new java.awt.Color(255, 255, 255));
        btnProcess.setText("Process >>>");
        btnProcess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Process NGO Requests");

        tblRnDProcess.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No", "Medicine", "Quantity", "Expiry"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblRnDProcess);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(btnProcess, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(193, 193, 193)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(296, 296, 296)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(257, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnProcess)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnProcessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessActionPerformed
        // TODO add your handling code here:NGODonationDetailsJPanel
        
        int selectedRow = tblRnDProcess.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        System.out.println(selectedRow+" selectedRow is");
        NGOtoRNDWorkRequest request = (NGOtoRNDWorkRequest)tblRnDProcess.getValueAt(selectedRow, 0);
        System.out.println(request.getMedicine()+" med is");
//        RnDProcessRequestJPanel rnDProcessRequestJPanel = new RnDProcessRequestJPanel(userProcessContainer,request);
//        userProcessContainer.add("rnDProcessRequestJPanel", rnDProcessRequestJPanel);
//        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
//        layout.next(userProcessContainer);
        
        RnDProcessRequestJPanel rnDProcessRequestJPanel = new RnDProcessRequestJPanel(userProcessContainer,request);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("rnDProcessRequestJPanel", rnDProcessRequestJPanel);
        layout.next(userProcessContainer);

    }//GEN-LAST:event_btnProcessActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProcess;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRnDProcess;
    // End of variables declaration//GEN-END:variables

    private void populateRnDRequestTable() {
//        userAccount.getWorkQueue().getWorkRequestList();
        System.out.println("in populateRnDRequestTable() ");
        DefaultTableModel model = (DefaultTableModel)tblRnDProcess.getModel();
        
        model.setRowCount(0);
        
        for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof RnDOrganization) {
                System.out.println(org+"-------in org instanceof RnDOrganization ");
                for (UserAccount user : org.getUserAccountList().getUserAccountList()) {
                    if (user.equals(userAccount)) {
                        System.out.println(user+"-------user "+"---userAccount"+userAccount);
                        for(WorkRequest request : org.getWorkQueue().getWorkRequestList())
                        {
                            Object[] row = new Object[4];
                            System.out.println(request.getMedicine().getMedicineName()+"-----requesust get med name ");
                            row[0] = request;
                            row[1] =  request.getSender();
                            row[2] = request.getStatus();
                            row[3] = request.getMedicine();
                             model.addRow(row);
                        }
                        
                        break;
                    }

                }

            }

        }
        
       
//        
//        for(WorkRequest request : enterp.getWorkQueue().getWorkRequestList()){
//            Object[] row = new Object[5];
//            
//            
//            // nikunj 5/12
//            row[0] = request;
//            row[1] = request.getMedicine().getMedicineName();
//            row[2] = request.getMedicine().getQuantity();
//            row[3] = request.getMedicine().getExpiryDate();
//            row[4] = request.getStatus();
//            
//            model.addRow(row);
//        }
        
    }
}
