/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Disposable;

import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author NIKUNJ
 */
public class DisposableWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisposableWorkAreaJPanel
     */
    
    JPanel container;
    Enterprise enterprise;
    Network network;
    UserAccount userAccount;
    
    

    public DisposableWorkAreaJPanel(JPanel container, Enterprise enterprise, Network network, UserAccount userAccount) {
        initComponents();
        this.container=container;
        this.enterprise=enterprise;
        this.network=network;
        this.userAccount=userAccount;
                               
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
        // nikunj singh 4/12

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMnageInventory = new javax.swing.JButton();
        btnListRequest = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        disIN = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        btnMnageInventory.setBackground(new java.awt.Color(51, 153, 255));
        btnMnageInventory.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnMnageInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnMnageInventory.setText("Manage Inventory");
        btnMnageInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMnageInventoryActionPerformed(evt);
            }
        });

        btnListRequest.setBackground(new java.awt.Color(51, 153, 255));
        btnListRequest.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnListRequest.setForeground(new java.awt.Color(255, 255, 255));
        btnListRequest.setText("List Of Request");
        btnListRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListRequestActionPerformed(evt);
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Disposable Work Area");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(444, 444, 444)
                .addComponent(jLabel1)
                .addContainerGap(455, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(78, 78, 78))
        );

        disIN.setBackground(new java.awt.Color(255, 255, 255));
        disIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                disINMouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(51, 102, 255));
        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 255));
        jLabel15.setText("Disposable");

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 153, 255));
        jLabel16.setText("Inventory");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/Images/icons8-warehouse-filled-100.png"))); // NOI18N

        javax.swing.GroupLayout disINLayout = new javax.swing.GroupLayout(disIN);
        disIN.setLayout(disINLayout);
        disINLayout.setHorizontalGroup(
            disINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(disINLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(disINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addGroup(disINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, disINLayout.createSequentialGroup()
                            .addComponent(jLabel15)
                            .addGap(4, 4, 4))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        disINLayout.setVerticalGroup(
            disINLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, disINLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addGap(21, 21, 21)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(529, 529, 529)
                    .addComponent(disIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(596, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(256, 256, 256)
                    .addComponent(disIN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMnageInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMnageInventoryActionPerformed
       
    }//GEN-LAST:event_btnMnageInventoryActionPerformed

    private void btnListRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListRequestActionPerformed
        // TODO add your handling code here:
       
      
    }//GEN-LAST:event_btnListRequestActionPerformed

    private void disINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_disINMouseClicked
        // TODO add your handling code here:

        DisposableInventoryJPanel disposableInventoryJPanel = new DisposableInventoryJPanel(container, enterprise, userAccount, network);
        CardLayout layout = (CardLayout) container.getLayout();
        container.add("disposableInventoryJPanel", disposableInventoryJPanel);
        layout.next(container);

    }//GEN-LAST:event_disINMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListRequest;
    private javax.swing.JButton btnMnageInventory;
    private javax.swing.JPanel disIN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
