/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGORole;

import Business.Enterprise.DisposableEnterprise;
import Business.Enterprise.Enterprise;
//import static Business.Enterprise.Enterprise.EnterpriseType.Hospital;
import Business.Enterprise.HospitalEnterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Inventory.InventoryItem;
import Business.Inventory.NGOInventoryItem;
import Business.Medicine.Medicine;
import Business.Network.Network;
import Business.Organization.ManagerOrganization;
import Business.Organization.Organization;
import Business.Organization.RnDOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.NGODonationRequest;
import Business.WorkQueue.NGOtoRNDWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita Mhatre
 */
public class NGOApproveRequestJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOApproveRequestJPanel
     */
    private JPanel userProcessContainer;
   private Network network;
    private Enterprise enterprise;
    private UserAccount userAccount;
    
    int medQuantity;
    Medicine m;
    
//    private NGOEnterprise ngoEnterprise;
    
//    ********Ankita 11/29***********
    
//    private NGOInventoryItem ngoInventory;
    
    public NGOApproveRequestJPanel(JPanel userProcessContainer,Enterprise enterprise, Network network, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
        this.network = network;
//        this.ngoEnterprise = (NGOEnterprise)enterprise;
        System.out.println(enterprise+"------------ngo enterprise");
        populateManageRequestTable();
                
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageRequest = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtBackButton = new javax.swing.JButton();
        btnSendtoRandD = new javax.swing.JButton();

        tblManageRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User", "Medicine", "Quantity", "Expiry", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblManageRequest);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Approve ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Manage Request");

        txtBackButton.setText("<<< Back");
        txtBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackButtonActionPerformed(evt);
            }
        });

        btnSendtoRandD.setBackground(new java.awt.Color(0, 102, 204));
        btnSendtoRandD.setForeground(new java.awt.Color(255, 255, 255));
        btnSendtoRandD.setText("Send to R&D Team");
        btnSendtoRandD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendtoRandDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(btnSendtoRandD, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(355, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtBackButton))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(btnSendtoRandD))
                .addContainerGap(236, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_txtBackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
//        ********* Ankita 11/29 ***********
        int selectedRow = tblManageRequest.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        
        NGODonationRequest request = (NGODonationRequest)tblManageRequest.getValueAt(selectedRow, 0);
        medQuantity = request.getMedicine().getQuantity();
        m = request.getMedicine();
        
        System.out.println(medQuantity+"---------med quantity");
        request.setStatus("Accepted");
        System.out.println(enterprise+"---------enterprise in ngo approve req");

        enterprise.getInventoryDirectoryEnterpriseLevel().addInventoryItem(enterprise, userAccount, m, medQuantity);
                 
             populateManageRequestTable();        
//         ********* Ankita 11/29 ***********
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSendtoRandDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendtoRandDActionPerformed
        // TODO add your handling code here:
//        ********* Ankita 11/29 ***********
        
        int selectedRow = tblManageRequest.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        
        NGODonationRequest request = (NGODonationRequest)tblManageRequest.getValueAt(selectedRow, 0);
     
        request.setStatus("Processing");
        NGOtoRNDWorkRequest rndrequest = new NGOtoRNDWorkRequest();
        rndrequest.setMedicine(request.getMedicine());
        rndrequest.setSender(userAccount);
        rndrequest.setStatus("sent");
    
            for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList()) {
            if (org instanceof RnDOrganization) {
                for (UserAccount user : org.getUserAccountList().getUserAccountList()) {
                    rndrequest.setReceiver(user); 
                        org.getWorkQueue().addRequest(rndrequest);
                        user.getWorkQueue().addRequest(rndrequest);
                        break;
                    
                }

            }

        }
    
    
//        ********* Ankita 11/29 ***********
        
    }//GEN-LAST:event_btnSendtoRandDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
//        ********* Ankita 11/29 ***********
                int selectedRow = tblManageRequest.getSelectedRow();
        if (selectedRow < 0){
            return;
        }
        
        NGODonationRequest request = (NGODonationRequest)tblManageRequest.getValueAt(selectedRow, 0);
        
     
        
        request.setStatus("Denied");
        
        populateManageRequestTable();
        
//        ********* Ankita 11/29 ***********
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendtoRandD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageRequest;
    private javax.swing.JButton txtBackButton;
    // End of variables declaration//GEN-END:variables

    private void populateManageRequestTable() {
        DefaultTableModel model = (DefaultTableModel)tblManageRequest.getModel();
        
        model.setRowCount(0);

        Enterprise enterp = null;
        for (Enterprise ent : network.getEnterpriseDirectory().getEnterpriseList()){
//            System.out.println(ent.getEnterpriseType().getValue()+"<-------here");
            if (ent.getEnterpriseType().getValue().equals("Hospital Enterprise") && ent instanceof HospitalEnterprise){
                
                enterp = ent;
                break;
            }
        }
        
        for(WorkRequest request : enterp.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            
            // nikunj 5/12
            row[0] = request;
            row[1] = request.getMedicine().getMedicineName();
            row[2] = request.getMedicine().getQuantity();
            row[3] = request.getMedicine().getExpiryDate();
            row[4] = request.getStatus();
            model.addRow(row);
        }

    }
}
