/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGORole;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Ankita Mhatre
 */

public class NGODonationDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGODonationDetailsJPanel
     */
    private JPanel userProcessContainer;
    public NGODonationDetailsJPanel(JPanel userProcessContainer) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMedName = new javax.swing.JLabel();
        lblPrescribed = new javax.swing.JLabel();
        lblExpiryDate = new javax.swing.JLabel();
        lblDisease = new javax.swing.JLabel();
        lblDoctorName = new javax.swing.JLabel();
        lblComment = new javax.swing.JLabel();
        textDisease = new javax.swing.JTextField();
        lblQuantity = new javax.swing.JLabel();
        textPrescibedMedicine2 = new javax.swing.JTextField();
        lblDrugType = new javax.swing.JLabel();
        textFirstName = new javax.swing.JTextField();
        textLastName = new javax.swing.JTextField();
        textTime = new javax.swing.JTextField();
        textAge = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        textPrescibedMedicine3 = new javax.swing.JTextField();
        textDisease1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtBackButton = new javax.swing.JButton();

        lblMedName.setText("Medicine Name");

        lblPrescribed.setText("Prescribed ? ");

        lblExpiryDate.setText("Expiry Date");

        lblDisease.setText("Disease");

        lblDoctorName.setText("Doctor Name");

        lblComment.setText("Comment");

        textDisease.setEditable(false);

        lblQuantity.setText("Quantity");

        textPrescibedMedicine2.setEditable(false);
        textPrescibedMedicine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrescibedMedicine2ActionPerformed(evt);
            }
        });

        lblDrugType.setText("Drug Type");

        textFirstName.setEditable(false);

        textLastName.setEditable(false);

        textTime.setEditable(false);

        textAge.setEditable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Details");

        textPrescibedMedicine3.setEditable(false);
        textPrescibedMedicine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textPrescibedMedicine3ActionPerformed(evt);
            }
        });

        textDisease1.setEditable(false);

        jButton1.setBackground(new java.awt.Color(0, 102, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Approve ");

        txtBackButton.setText("<<< Back");
        txtBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(textDisease1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textPrescibedMedicine3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textTime, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textPrescibedMedicine2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textDisease, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(195, 195, 195)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(txtBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(296, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(217, 217, 217)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblMedName)
                        .addComponent(lblQuantity)
                        .addComponent(lblExpiryDate)
                        .addComponent(lblDoctorName)
                        .addComponent(lblDrugType)
                        .addComponent(lblPrescribed)
                        .addComponent(lblDisease)
                        .addComponent(lblComment))
                    .addContainerGap(476, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(txtBackButton)))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addComponent(textLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addComponent(textTime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(textAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPrescibedMedicine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textDisease1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textPrescibedMedicine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDisease, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jButton1)
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(lblMedName)
                    .addGap(18, 18, 18)
                    .addComponent(lblQuantity)
                    .addGap(18, 18, 18)
                    .addComponent(lblExpiryDate)
                    .addGap(26, 26, 26)
                    .addComponent(lblDoctorName)
                    .addGap(18, 18, 18)
                    .addComponent(lblDrugType)
                    .addGap(18, 18, 18)
                    .addComponent(lblPrescribed)
                    .addGap(18, 18, 18)
                    .addComponent(lblDisease)
                    .addGap(18, 18, 18)
                    .addComponent(lblComment)
                    .addContainerGap(233, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void textPrescibedMedicine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrescibedMedicine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrescibedMedicine2ActionPerformed

    private void textPrescibedMedicine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textPrescibedMedicine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textPrescibedMedicine3ActionPerformed

    private void txtBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_txtBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblComment;
    private javax.swing.JLabel lblDisease;
    private javax.swing.JLabel lblDoctorName;
    private javax.swing.JLabel lblDrugType;
    private javax.swing.JLabel lblExpiryDate;
    private javax.swing.JLabel lblMedName;
    private javax.swing.JLabel lblPrescribed;
    private javax.swing.JLabel lblQuantity;
    private javax.swing.JTextField textAge;
    private javax.swing.JTextField textDisease;
    private javax.swing.JTextField textDisease1;
    private javax.swing.JTextField textFirstName;
    private javax.swing.JTextField textLastName;
    private javax.swing.JTextField textPrescibedMedicine2;
    private javax.swing.JTextField textPrescibedMedicine3;
    private javax.swing.JTextField textTime;
    private javax.swing.JButton txtBackButton;
    // End of variables declaration//GEN-END:variables
}
