/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.NGORole;

import Business.Inventory.InventoryItem;
import Business.Inventory.NGOInventoryItem;
import Business.Medicine.Medicine;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita Mhatre
 */
public class NGOInventoryItemDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NGOInventoryItemDetailsJPanel
     */
    private JPanel userProcessContainer;
    private NGOInventoryItem ngoInventoryItem;
    public NGOInventoryItemDetailsJPanel(JPanel userProcessContainer, NGOInventoryItem ngoInventoryItem) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ngoInventoryItem = ngoInventoryItem;
        populateTblinventoryItemView();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblinventoryItemView = new javax.swing.JTable();
        txtBackButton = new javax.swing.JButton();

        tblinventoryItemView.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Quantity", "Expiry", "Medical Condition", "Comments"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblinventoryItemView);

        txtBackButton.setText("<<< Back");
        txtBackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtBackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(txtBackButton)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(152, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBackButtonActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_txtBackButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblinventoryItemView;
    private javax.swing.JButton txtBackButton;
    // End of variables declaration//GEN-END:variables

    private void populateTblinventoryItemView() {
        DefaultTableModel model = (DefaultTableModel) tblinventoryItemView.getModel();

        model.setRowCount(0);
        for(Medicine m : ngoInventoryItem.getMedicineListInInventoryItem().getMedicineList())
        {
            System.out.println(m.getMedicineName()+"-----------med name fro medlist");
            Object[] row = new Object[5];
            row[0] = m;
            row[1] = m.getQuantity();
            row[2] = m.getExpiryDate();
            row[3] = m.getDisease();
            row[4] = m.getComment();
            model.addRow(row);
        }
    }
    
}
