/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SystemAdmin;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.NGOEnterprise;
import Business.Inventory.InventoryItem;
import Business.Medicine.Medicine;
import Business.Network.Network;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ankita Mhatre
 */
public class MedicineAnalyserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form MedicineAnalyserJPanel
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    public MedicineAnalyserJPanel(JPanel userProcessContainer, EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAllNetworks3 = new javax.swing.JLabel();
        txtMedName = new javax.swing.JTextField();
        btnTotalMeds = new javax.swing.JButton();
        lblAllNetworks = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSuggestions = new javax.swing.JTable();
        btnBack2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        lblAllNetworks3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAllNetworks3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAllNetworks3.setText("Medicines");

        txtMedName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtMedName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMedNameActionPerformed(evt);
            }
        });

        btnTotalMeds.setBackground(new java.awt.Color(51, 153, 255));
        btnTotalMeds.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTotalMeds.setForeground(new java.awt.Color(255, 255, 255));
        btnTotalMeds.setText("Get Medicine");
        btnTotalMeds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalMedsActionPerformed(evt);
            }
        });

        lblAllNetworks.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblAllNetworks.setText("Enter Medical Condition");

        tblSuggestions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sr No", "Medicine"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblSuggestions);

        btnBack2.setText("<< Back Button");
        btnBack2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setText("Medicne Analyzer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblAllNetworks3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAllNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTotalMeds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(455, 455, 455)
                        .addComponent(jLabel1)))
                .addContainerGap(365, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(btnBack2)
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMedName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAllNetworks, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnTotalMeds)
                .addGap(30, 30, 30)
                .addComponent(lblAllNetworks3)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMedNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMedNameActionPerformed

    private void btnTotalMedsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalMedsActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblSuggestions.getModel();
        model.setRowCount(0);
        Object[] row = new Object[50];
        int srno = 1;
            String diseaseName = txtMedName.getText();
            System.out.println(diseaseName + "condotion name");
            for (Network network : business.getNetworkList()) {
            System.out.println(network + "---network");
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof NGOEnterprise) {
                    System.out.println(enterprise.getName() + "---should be ngo enterprise");
                    for (InventoryItem i : enterprise.getInventoryDirectoryEnterpriseLevel().getInventoryList()) {
                        System.out.println(i.getMedName() + "inv item name");
                        for(Medicine m : i.getMedicineListInInventoryItem().getMedicineList())
                        {
                            System.out.println(m + "inv med name");
                            if(diseaseName.equalsIgnoreCase(m.getDisease()))
                            {
                                System.out.println(m.getDisease() + "disease found");
                                System.out.println(m.getMedicineName() + "disease med name");
                                row[0] = srno;
                                row[1] = m.getMedicineName();
                                srno ++;
                                model.addRow(row);
                            }
                        }
                    }

                }
            }
           
        }
    }//GEN-LAST:event_btnTotalMedsActionPerformed

    private void btnBack2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBack2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack2;
    private javax.swing.JButton btnTotalMeds;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAllNetworks;
    private javax.swing.JLabel lblAllNetworks3;
    private javax.swing.JTable tblSuggestions;
    private javax.swing.JTextField txtMedName;
    // End of variables declaration//GEN-END:variables
}
